// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/passport-http-bearer/passport-http-bearer.d.ts
declare module "passport-http-bearer" {

    import passport = require("passport");
    import express = require("express");

    interface IStrategyOptions {
        scope: string | Array<string>;
        realm: string;
        passReqToCallback: boolean;
    }
    interface IVerifyOptions {
        message: string;
        scope: string | Array<string>;
    }

    interface VerifyFunction {
        (token: string, done: (error: any, user?: any, options?: IVerifyOptions | string) => void): void;
    }

    interface VerifyFunctionWithRequest {
        (req: express.Request, token: string, done: (error: any, user?: any, options?: IVerifyOptions | string) => void): void;
    }

    class Strategy implements passport.Strategy {
        constructor(verify: VerifyFunction);
        constructor(options: IStrategyOptions, verify: VerifyFunction);
        constructor(options: IStrategyOptions, verify: VerifyFunctionWithRequest);

        name: string;
        authenticate: (req: express.Request, options?: Object) => void;
    }
}
